# Lug'atlar
[[translations]]
en = "Infiltrating"
uz = "Kirish"
description = ""
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "Debug"
uz = "Debag"
description = "Kod yozishda xatolik kelib chiqsa kodni debag qilish kerak bo ªladi"
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "Debugging"
uz = "Debaglash"
description = ""
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "Sensor"
uz = "Sensor"
description = ""
pronunciation_uz = "sensr"
similar = [""]

[[translations]]
en = "Multithread"
uz = "Ko'p oqimli"
description = "Ko'p oqimli ishlov berish jarayoni haqida atama."
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "Single thread"
uz = "Bir oqimli"
description = "Bitta oqim bilan ishlaydigan jarayon."
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "Concurrency"
uz = "Parallel ishlash"
description = "Bir nechta vazifalarni bir vaqtda boshqarish."
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "parse"
uz = "pars"
description = ""
pronunciation_uz = "pars"
similar = [""]

[[translations]]
en = "parsing"
uz = "parsing"
description = ""
pronunciation_uz = "parsing"
similar = [""]

[[translations]]
en = "IT"
uz = "AyTi"
description = ""
pronunciation_uz = "ayti"
similar = [""]

[[translations]]
en = "Authentication"
uz = "Tasdiqlash"
description = ""
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "Authorization"
uz = "Ruxsat"
description = "tasdiqlash deb tarjima chiqyapti lekin ruxsat ma'nosida keldi ko'pincha meni tajribamda"
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "Option"
uz = "Tanlov"
description = ""
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "Framework"
uz = "Freymvork"
description = ""
pronunciation_uz = "Freymvo'rk"
similar = [""]

[[translations]]
en = "Folder"
uz = "Jild"
description = ""
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "Directory"
uz = "Katalog"
description = ""
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "Branch"
uz = ""
description = ""
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "account"
uz = "hisob"
description = ""
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "username"
uz = "User nomi"
description = ""
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "Advanced"
uz = ""
description = "qiyinchilik darajasi"
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "layout"
uz = ""
description = ""
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "release"
uz = ""
description = ""
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "Category"
uz = "Tasnif"
description = ""
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "Original"
uz = "Asl nusxa"
description = ""
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "Fuzzy"
uz = ""
description = ""
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "Progress"
uz = ""
description = ""
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "Error"
uz = ""
description = ""
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "Reviewer"
uz = ""
description = ""
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "Review"
uz = ""
description = ""
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "workflow"
uz = ""
description = ""
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "scrape"
uz = ""
description = ""
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "Repository"
uz = ""
description = ""
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "Feedback"
uz = "Sharh"
description = ""
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "Firmware"
uz = ""
description = ""
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "charge"
uz = "quvvat"
description = ""
pronunciation_uz = ""
similar = ["zaryadlash"]

[[translations]]
en = "citizen"
uz = "vatandosh"
description = ""
pronunciation_uz = ""
similar = ["fuqaro"]

[[translations]]
en = "Two-step verification"
uz = "Ikki bosqichli tasdiqlash"
description = ""
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "copy"
uz = "nusxa olish"
description = ""
pronunciation_uz = ""
similar = ["nusxalash"]

[[translations]]
en = "favorites"
uz = "saralanganlar"
description = ""
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "e-mail"
uz = "e-pochta"
description = ""
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "mail"
uz = "pochta"
description = ""
pronunciation_uz = ""
similar = [""]

[[translations]]
en = "suspend"
uz = "uyqu holati"
description = "kopyuterni dipleyini o'chitib qo'yish lekin quvvatdan uzilmagan holda"
pronunciation_uz = ""
similar = ["sleep"]

[[translations]]
en = "matherboard"
uz = "ona plata"
description = ""
pronunciation_uz = ""
similar = ["bosh plata", "bosh qismi iya"]

[[translations]]
en = "emoji"
uz = "hisbelgi"
description = ""
pronunciation_uz = ""
similar = [""]
